def is_server_running?(port)
  system("lsof -i:#{port}", out: '/dev/null')
end

def server_not_running_error
  STDERR.puts '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
  STDERR.puts 'One or more acceptance tests are failing.'
  STDERR.puts '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
  exit 1
end

def step_has_error?(command)
    command = command.delete(' ')
    stats = get_summary(command)    
    return is_there_an_error?(stats)
end

def get_summary(output)
    str1 = "StepsSummary:"
    str1_length = str1.length
    str2 = "Finished"
    i1 = output.index(str1) + str1_length
    i2 = output.index(str2) - 1
    summary = output[i1..i2]
    return get_summary_arr(summary)
end

def get_summary_arr(summary)
    stats = summary.split(",")
    stats = stats.slice(1, 4)
    return stats
end

def is_there_an_error?(stats)
  stats.each do |stat| 
    if stat[2] != "0"
      return true
    end
  end
  return false
end

desc "Run all of the tests in the suite"
task :test do
  if is_server_running?(5000)
    puts `bundle exec spinach`
  else
    server_not_running_error()
  end
end

namespace :test do
  desc "Run all of the tests in 01_getting_started"
  task :f1 do
    if is_server_running?(5000)
#       command = `bundle exec spinach --tags 01-getting-started`
#       puts command
      command = %x[echo `bundle exec spinach --tags 01-getting-started`]
      if step_has_error?(command)
        exit 1
      end
    else
      server_not_running_error()
    end
  end

  desc "Run all of the tests in 02_structured_data"
  task :f2 do
    if is_server_running?(5000)
#       command = `bundle exec spinach --tags 02-structured-data`
      command = %x[echo `bundle exec spinach --tags 02-structured-data`]
      if step_has_error?(command)
        exit 1
      end
    else
      server_not_running_error()
    end
  end

  desc "Run all of the tests in 03_file_server"
  task :f3 do
    if is_server_running?(5000)
#       command = `bundle exec spinach --tags 03-file-server`
      command = %x[echo `bundle exec spinach --tags 03-file-server`]
      if step_has_error?(command)
        exit 1
      end
    else
      server_not_running_error()
    end
  end

  desc "Run all of the tests in 04_todo_list"
  task :f4 do
    if is_server_running?(5000)
      command = `bundle exec spinach --tags 04-todo-list`
      puts command
      if step_has_error?(command)
        exit 1
      end
    else
      server_not_running_error()
    end
  end
end

desc "Start a demo server with working endpoints"
task :server do
  `ruby server.rb`
end
