name: Deploy to an Azure Virtual Machine

env:
  OUTPUT_PATH: ${{ github.workspace }}
  DOTNET_VERSION: '6.0.x'


on: push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish with dotnet
        run: dotnet publish -c Release -r linux-x64 --self-contained true
        working-directory: HTTPServerProject

      - name: Run a multi-line script
        run: |
          mkdir ../build
          cp -TR . ../build
          tar -cvf deploy.tar ../build/

      - name: Copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.VIRTUAL_MACHINE_SECURITY_KEY }}
          source: "deploy.tar"
          target: "home/${{ secrets.USERNAME }}/"

      - name: Open IP Address with ssh
        run: ssh ${{ secrets.VM_IP_ADDRESS }}

      - name: Run program with dotnet
        run: dotnet linux-x64/HTTPServer.dll 
      