name: Deploy to an Azure Virtual Machine

env:
  OUTPUT_PATH: ${{ github.workspace }}
  DOTNET_VERSION: '6.0.x'


on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish with dotnet
        run: dotnet publish -c Release -r linux-x64 --self-contained true
        working-directory: HTTPServerProject

      - name: Copy to remote machine with scp
        run: scp -r HTTPServerProject/bin/Release/net6.0/linux-x64/ ${{ secrets.VM_IP_ADDRESS_FULL }}

      - name: Open IP Address with ssh
        run: ssh ${{ secrets.VM_IP_ADDRESS }}

      - name: Run program with dotnet
        run: dotnet linux-x64/HTTPServer.dll 
      