name: .NET

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Restore dependencies
      run: dotnet restore HTTPServerProject
    - name: Build
      run: dotnet build --no-restore HTTPServerProject
    - name: Test
      run:  |
        nohup dotnet run --project HTTPServerProject &    
        dotnet test --verbosity normal HTTPServerProject.Tests 
    - name: Install Bundle
      run:  |
        cd http-server-spec
        bundle install
    - name: Acceptance Tests
      run:  |
        nohup dotnet run --project HTTPServerProject &
        cd http-server-spec
        bundle exec rake acctest:f1
        bundle exec rake acctest:f2
        bundle exec rake acctest:f3

