name: .NET

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
    - name: Restore dependencies
      run: dotnet restore HTTPServerProject
    - name: Build
      run: dotnet build --no-restore HTTPServerProject
    - name: Test
      run: dotnet test --no-build --verbosity normal HTTPServerProject.Tests
    - name: Run
      run: nohup dotnet run --project HTTPServerProject &
    - name: Acceptance Tests
      run:  | 
        cd http-server-spec
        bundle install
        rake test:f1
        rake test:f2
        rake test:f3
        rake test:f4

